// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: '/api',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR'],
  credentialsKey: 'credentials',
  poolData: {
    ClientId: 'COGNITO_CLIENT_ID',
    UserPoolId: 'COGNITO_USED_POOL_ID'
  }
};
